# 1-D Arry

In [99]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


# 2-D Array

In [100]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


 # Zero Matrix initilization

In [101]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrenging num x And y interval of z

In [102]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Arrangingg z values between x & y


In [103]:
np.linspace(5
,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [104]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [105]:
# for even num
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling same num


In [106]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# Filling random num


In [107]:
np.random.rand(3,4)

array([[0.85615333, 0.11076031, 0.44860024, 0.29769813],
       [0.46392172, 0.89496701, 0.86085007, 0.75289473],
       [0.65034899, 0.79989983, 0.16402516, 0.40274494]])

# Inspection of arry checking the size of the array


In [108]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [109]:
a=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4]])
print(a.shape)

(3, 4)


In [110]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.shape)

(1, 3, 4)


# Resize the array

In [111]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [112]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
a.shape=(3,4)
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]


# Return dimention of array

In [113]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a)
print(a.ndim)
# Check the shape of the array and reshape it to (3,4) if possible. If not possible, print an error message.

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 4]]]
3


# Find the Num Element in Array

In [114]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.size)

12


# Find the datatype of the array

In [115]:

a=np.arange(24, dtype=float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [116]:

a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
