# 1-D Arry

In [64]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


# 2-D Array

In [65]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


 # Zero Matrix initilization

In [66]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrenging num x And y interval of z

In [67]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Arrangingg z values between x & y


In [68]:
np.linspace(5
,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [69]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [70]:
# for even num
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling same num


In [71]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# Filling random num


In [72]:
np.random.rand(3,4)

array([[0.81535326, 0.83665574, 0.03320398, 0.27662112],
       [0.25969014, 0.18278409, 0.70221077, 0.83464768],
       [0.55078667, 0.47381858, 0.87950354, 0.89989271]])

# Inspection of arry checking the size of the array


In [73]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [74]:
a=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4]])
print(a.shape)

(3, 4)


In [75]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.shape)

(1, 3, 4)


# Resize the array

In [76]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [77]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
a.shape=(3,4)
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]


# Return dimention of array

In [78]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a)
print(a.ndim)
# Check the shape of the array and reshape it to (3,4) if possible. If not possible, print an error message.

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 4]]]
3


# Find the Num Element in Array

In [79]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.size)

12


# Find the datatype of the array

In [80]:

a=np.arange(24, dtype=float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [81]:

a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Addition


In [82]:
import numpy as np
np.sum([10,20])

np.int64(30)

In [83]:
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

In [84]:
np.sum([[1,2],[5,6]])


np.int64(14)

In [85]:
np.sum([[1,2],[5,6]],axis=1)


array([ 3, 11])

# substraction

In [86]:
np.subtract(10,20)

np.int64(-10)

In [87]:
np.subtract([10,20],[5,10])

array([ 5, 10])

# All other operations on numpy

In [88]:
np.multiply(10,20)

np.int64(200)

In [89]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.multiply(a,b)

array([ 4, 10, 18])

In [90]:
np.divide(20,10)

np.float64(2.0)

In [91]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [92]:
#exponent
np.exp(a)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [93]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [94]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [95]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [96]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

# Array comparision

In [97]:
a=[1,2,3]
b=[4,2,6]
c=[4,2,3]
np.equal(c,b)


array([ True,  True, False])

In [98]:
a=[1,2,3]
b=[4,2,6]
c=[4,2,6]
print(np.array_equal(a,b))
np.array_equal(c,b)

False


True

# Aggregate Function

In [99]:
a=np.array([1,2,3,4,5,6])
print("sum:",np.sum(a))
print("mean:",np.mean(a))
print("max:",np.max(a))
print("min:",np.min(a))
print("standard deviation:",np.std(a))
print("variance:",np.var(a))
print("median:",np.median(a))
print("coorelation coefficient:",np.corrcoef(a))


sum: 21
mean: 3.5
max: 6
min: 1
standard deviation: 1.707825127659933
variance: 2.9166666666666665
median: 3.5
coorelation coefficient: 1.0


# Brodcasting

In [100]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,1])
a+b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Array Manupalation

In [101]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [102]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [103]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Spliting Function

In [105]:
a=np.arange(16).reshape(4,4)
print(a)
print()
print(np.hsplit(a,2))
print(np.vsplit(a,2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# index Slicing

In [106]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a,"\n\n")
print(a[2])
print("\n\n",a[:1,1:])
print("\n\n",a[:2,1:])
print("\n\n",a[1:,])
a[:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 


[7 8 9]


 [[2 3]]


 [[2 3]
 [5 6]]


 [[4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

# ADVANTAGE OF ARRAY

In [112]:
import numpy as np
import sys
l=range(1000)
print("size of list:",sys.getsizeof(1)*len(l))

#numpy array
a=np.arange(1000)
print("size of numpy array:",sys.getsizeof(a))

size of list: 28000
size of numpy array: 8112


In [ ]:
import time
def using_list():
  t1=time.time()
  x=range(1000)
  y=range(1000)
  z=[x[i]+y[i] for i in range(len(x))]
  return time.time()-t1
def using_numpy():
  t1=time.time()
  x=np.arange(100000)
  y=np.arange(100000)
  z=x+y
  return time.time()-t1

In [118]:
print(using_list())

0.004357814788818359


In [119]:
print(using_numpy())

0.0
