# 1-D Arry

In [207]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


# 2-D Array

In [208]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


 # Zero Matrix initilization

In [209]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrenging num x And y interval of z

In [210]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Arrangingg z values between x & y


In [211]:
np.linspace(5
,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [212]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [213]:
# for even num
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling same num


In [214]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# Filling random num


In [215]:
np.random.rand(3,4)

array([[0.2752695 , 0.50376715, 0.76417271, 0.63738674],
       [0.94335116, 0.83097046, 0.40697913, 0.71351885],
       [0.84284787, 0.01790507, 0.27934701, 0.53015979]])

# Inspection of arry checking the size of the array


In [216]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [217]:
a=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,4]])
print(a.shape)

(3, 4)


In [218]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.shape)

(1, 3, 4)


# Resize the array

In [219]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [220]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
a.shape=(3,4)
print(a)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 4]]


# Return dimention of array

In [221]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a)
print(a.ndim)
# Check the shape of the array and reshape it to (3,4) if possible. If not possible, print an error message.

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 4]]]
3


# Find the Num Element in Array

In [222]:
a=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,4]]])
print(a.size)

12


# Find the datatype of the array

In [223]:

a=np.arange(24, dtype=float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [224]:

a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# Addition


In [225]:
import numpy as np
np.sum([10,20])

np.int64(30)

In [226]:
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

In [227]:
np.sum([[1,2],[5,6]])


np.int64(14)

In [228]:
np.sum([[1,2],[5,6]],axis=1)


array([ 3, 11])

# substraction

In [229]:
np.subtract(10,20)

np.int64(-10)

In [230]:
np.subtract([10,20],[5,10])

array([ 5, 10])

# All other operations on numpy

In [231]:
np.multiply(10,20)

np.int64(200)

In [232]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.multiply(a,b)

array([ 4, 10, 18])

In [233]:
np.divide(20,10)

np.float64(2.0)

In [234]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [235]:
#exponent
np.exp(a)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [236]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [237]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [238]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [239]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

# Array comparision

In [240]:
a=[1,2,3]
b=[4,2,6]
c=[4,2,3]
np.equal(c,b)


array([ True,  True, False])

In [241]:
a=[1,2,3]
b=[4,2,6]
c=[4,2,6]
print(np.array_equal(a,b))
np.array_equal(c,b)

False


True

# Aggregate Function

In [242]:
a=np.array([1,2,3,4,5,6])
print("sum:",np.sum(a))
print("mean:",np.mean(a))
print("max:",np.max(a))
print("min:",np.min(a))
print("standard deviation:",np.std(a))
print("variance:",np.var(a))
print("median:",np.median(a))
print("coorelation coefficient:",np.corrcoef(a))


sum: 21
mean: 3.5
max: 6
min: 1
standard deviation: 1.707825127659933
variance: 2.9166666666666665
median: 3.5
coorelation coefficient: 1.0


# Brodcasting

In [243]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,1])
a+b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Array Manupalation